[2024-02-01 00:51:45,283] 	INFO 	20 	id_data.py 	<module>() 	ID Data Started
[2024-02-01 00:51:45,855] 	INFO 	31 	id_data.py 	<module>() 	ID Data Ended
[2024-02-01 00:51:46,624] 	INFO 	24 	day_data.py 	<module>() 	Day Data Fusion Started
[2024-02-01 00:51:49,104] 	INFO 	71 	day_data.py 	<module>() 	Day Data Fusion Ended
[2024-02-01 00:51:50,726] 	INFO 	35 	pair_data.py 	<module>() 	Pair Data Fusion Started
[2024-02-01 00:52:03,189] 	INFO 	101 	pair_data.py 	<module>() 	Pair Data Fusion Ended
[2024-02-01 00:52:04,015] 	INFO 	36 	bribe_data.py 	<module>() 	Bribe Data Started
[2024-02-01 00:54:50,971] 	INFO 	157 	bribe_data.py 	<module>() 	Bribe Data Ended
[2024-02-01 00:54:51,754] 	INFO 	36 	fee_data.py 	<module>() 	Fee Data Started
[2024-02-01 00:57:01,229] 	INFO 	157 	fee_data.py 	<module>() 	Fee Data Ended
[2024-02-01 00:57:02,016] 	INFO 	37 	vote_data.py 	<module>() 	Vote Data Started
[2024-02-01 00:57:12,220] 	INFO 	116 	vote_data.py 	<module>() 	Vote Data Ended
[2024-02-01 00:57:13,031] 	INFO 	30 	revenue_data.py 	<module>() 	Revenue Data Started
[2024-02-01 00:57:22,233] 	INFO 	150 	revenue_data.py 	<module>() 	Revenue Data Ended
[2024-02-01 00:57:22,989] 	INFO 	20 	pool_data.py 	<module>() 	Pool Data Started
[2024-02-01 00:57:33,774] 	ERROR 	82 	pool_data.py 	<module>() 	Error occurred during Pool Data process. Error: {'code': -32000, 'message': 'execution aborted (timeout = 5s)'}
Traceback (most recent call last):
  File "pool_data.py", line 53, in <module>
    pool_data = contract_instance.functions.getActivePoolDistributions(pool_address).call()
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/web3/contract.py", line 970, in call
    return call_contract_function(
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/web3/contract.py", line 1525, in call_contract_function
    return_data = web3.eth.call(
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/web3/module.py", line 57, in caller
    result = w3.manager.request_blocking(method_str,
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/web3/manager.py", line 198, in request_blocking
    return self.formatted_response(response,
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/web3/manager.py", line 171, in formatted_response
    raise ValueError(response["error"])
ValueError: {'code': -32000, 'message': 'execution aborted (timeout = 5s)'}
[2024-02-01 01:10:23,166] 	INFO 	26 	emissions_data.py 	<module>() 	Emissions Data Started
[2024-02-01 01:10:32,111] 	INFO 	131 	emissions_data.py 	<module>() 	Emissions Data Ended
[2024-02-01 01:50:23,341] 	INFO 	20 	id_data.py 	<module>() 	ID Data Started
[2024-02-01 01:50:23,778] 	INFO 	31 	id_data.py 	<module>() 	ID Data Ended
[2024-02-01 01:50:24,405] 	INFO 	24 	day_data.py 	<module>() 	Day Data Fusion Started
[2024-02-01 01:50:26,098] 	INFO 	71 	day_data.py 	<module>() 	Day Data Fusion Ended
[2024-02-01 01:50:27,169] 	INFO 	35 	pair_data.py 	<module>() 	Pair Data Fusion Started
[2024-02-01 01:50:41,559] 	INFO 	101 	pair_data.py 	<module>() 	Pair Data Fusion Ended
[2024-02-01 01:50:42,385] 	INFO 	36 	bribe_data.py 	<module>() 	Bribe Data Started
[2024-02-01 01:53:34,195] 	INFO 	157 	bribe_data.py 	<module>() 	Bribe Data Ended
[2024-02-01 01:53:35,065] 	INFO 	36 	fee_data.py 	<module>() 	Fee Data Started
[2024-02-01 01:55:34,528] 	INFO 	157 	fee_data.py 	<module>() 	Fee Data Ended
[2024-02-01 01:55:35,397] 	INFO 	37 	vote_data.py 	<module>() 	Vote Data Started
[2024-02-01 01:55:46,157] 	INFO 	116 	vote_data.py 	<module>() 	Vote Data Ended
[2024-02-01 01:55:47,038] 	INFO 	30 	revenue_data.py 	<module>() 	Revenue Data Started
[2024-02-01 01:55:58,494] 	INFO 	150 	revenue_data.py 	<module>() 	Revenue Data Ended
[2024-02-01 01:55:59,269] 	INFO 	20 	pool_data.py 	<module>() 	Pool Data Started
[2024-02-01 01:56:07,906] 	ERROR 	82 	pool_data.py 	<module>() 	Error occurred during Pool Data process. Error: {'code': -32000, 'message': 'execution aborted (timeout = 5s)'}
Traceback (most recent call last):
  File "pool_data.py", line 53, in <module>
    pool_data = contract_instance.functions.getActivePoolDistributions(pool_address).call()
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/web3/contract.py", line 970, in call
    return call_contract_function(
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/web3/contract.py", line 1525, in call_contract_function
    return_data = web3.eth.call(
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/web3/module.py", line 57, in caller
    result = w3.manager.request_blocking(method_str,
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/web3/manager.py", line 198, in request_blocking
    return self.formatted_response(response,
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/web3/manager.py", line 171, in formatted_response
    raise ValueError(response["error"])
ValueError: {'code': -32000, 'message': 'execution aborted (timeout = 5s)'}
